# Permission Providers : LuckPerms, PermissionsEx, Custom
# if the permission provider is custom, edit the settings lines.
permission_provider: LuckPerms
settings:
  # custom provider types : YAML, SQLite
  type: YAML
  # Chat listener priorities: LOWEST, LOW, NORMAL, HIGH, HIGHEST, MONITOR
  listener_priority: LOWEST
disabled_groups:
  - VIP
  - ExampleVIP
menu:
  title: "&aRank Menu"
  size: 5 # Minimum 1, Maximum 6
  panes:
    rank:
      x: 0
      y: 0
      height: 4
      length: 9
    up_down_info:
      x: 0
      y: 4
      height: 1
      length: 9
      empty_fill:
        status: true
        icon:
          material: STAINED_GLASS_PANE:0
          amount: 1
          name: ' '
      elements:
        up:
          x: 8
          y: 0
        down:
          x: 0
          y: 0
        info:
          x: 4
          y: 0
