# Permission Providers : LuckPerms, PermissionsEx, Custom
# if the permission provider is custom, edit the settings lines.
permission_provider: LuckPerms
settings:
  # custom provider types : YAML, SQLite
  type: YAML
  # Chat listener priorities: LOWEST, LOW, NORMAL, HIGH, HIGHEST, MONITOR
  listener_priority: HIGHEST
disabled_groups:
  - VIP
  - ExampleVIP
units:
  day: " day "
  days: " days "
  hour: " hour "
  hours: " hours "
  minute: " minute "
  minutes: " minutes "
  second: " second "
  seconds: " seconds "
menu:
  title: "&aRank Menu"
  size: 5 # Minimum 1, Maximum 6 or DYNAMIC
  directionArrowsPosition: DOWN #TOP(min size 2), SIDE(min size 1), DOWN(min size 2)
  empty_fill:
    rank_container:
      status: true
      icon:
        material: STAINED_GLASS_PANE:0
        amount: 1
        name: ' '
    arrow_container:
      status: true
      icon:
        material: STAINED_GLASS_PANE:0
        amount: 1
        name: ' '
  elements:
    down_arrow:
      material: ARROW
      amount: 1
      name: '&c<--'
      lores:
        - '&eCurrent page: %currentPage%'
    up_arrow:
      material: ARROW
      amount: 1
      name: '&c-->'
      lores:
        - '&eCurrent page: %currentPage%'