name: SuperRankup
main: me.draww.superrup.Main
version: ${project.version}
author: draww
website: https://draww.me/
softdepend: [Vault, LuckPerms, PermissionsEx, PlaceholderAPI]
commands:
  rank:
    description: main command
    usage: /rank
permissions:
  superrup.*:
    default: false
    children:
      superrup.reload:
        default: op
        description: reload all configs
      superrup.menu:
        default: true
        description: open rank menu